stages:
  - build
  - test-backend

image: docker:19.03.12

services:
  - docker:dind

before_script:
  - apk update && apk add docker docker-compose
  - apt-get update  
  - apt-get install python3 python3-pip make 
  - pip3 install pytest requests
  - docker --version

# run_frontend_tests:
#   stage: test-frontend
#   image: node:14
#   before_script:
#     - npm install
#   script:
#     - npm run test

build:
  stage: build
  script:
    - docker-compose build
  

test-backend:
  stage: test-backend
  script:
    - docker-compose up -d
    - cd backend/tests
    - pytest -v
  
# deploy:
#   stage: deploy
#   image: docker:19.03.12
#   before_script:
#     - apk update && apk add docker-compose
#   script:
#     - docker-compose up -d

