stages:
  - test-frontend
  - build
  - deploy
  - test-backend

# run_frontend_tests:
#   stage: test-frontend
#   image: node:14
#   before_script:
#     - npm install
#   script:
#     - npm run test

build:
  stage: build
  image: docker:19.03.12
  before_script:
    - apk update && apk add docker-compose
  script:
    - docker-compose build
  
deploy:
  stage: deploy
  image: docker:19.03.12
  before_script:
    - apk update && apk add docker-compose
  script:
    - docker-compose up -d

run_backend_tests:
  stage: test-backend
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - pip install -r backend/requirements.txt
    - cd backend/tests
    - pytest -v