stages:
  - playgroound
  - test-backend
  - deploy

# run_frontend_tests:
#   stage: test-frontend
#   image: node:14
#   before_script:
#     - npm install
#   script:
#     - npm run test

playgroound:
  stage: playgroound
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk update && apk add docker docker-compose

  script:
    - docker-compose --version
    - docker-compose up -d

test-backend:
  stage: test-backend
  image: docker:19.03.12
  before_script:
    - apt-get update && apt-get install make
  script:
    - apt-get install python3-pip python3-dev -y
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - cd backend/tests
    - pytest -v
  
# deploy:
#   stage: deploy
#   image: docker:19.03.12
#   before_script:
#     - apk update && apk add docker-compose
#   script:
#     - docker-compose up -d

