stages:
  - test-backend

image: docker:19.03.12

cache:
  paths:
    - .cache/pip

services:
  - docker:dind

before_script:
  - apk update && apk add docker docker-compose
  - apk add python3 py3-pip 
  - pip3 install pytest requests

test-backend:
  stage: test-backend
  script:
    - docker-compose up
    - cd backend/tests
    - pytest -v
  
=======
  - test-frontend
  - build
  - deploy

run_backend_tests:
  stage: test-backend
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test



